class_name Sprites
extends RefCounted
## Loads and places the PNG sprites generated by tools/generate_sprites.py.
##
## Every sprite is 128 * footprint pixels wide and its footprint diamond sits flush with the
## bottom of the image, so placement only needs the texture size.

const DIR := "res://assets/sprites/"

static var _cache := {}

const CIVIC_SPRITES := {
	Constants.Building.POWER_COAL: "civic_coal",
	Constants.Building.POWER_WIND: "civic_wind",
	Constants.Building.POWER_NUCLEAR: "civic_nuclear",
	Constants.Building.WATER_PUMP: "civic_pump",
	Constants.Building.WATER_TOWER: "civic_tower",
	Constants.Building.POLICE: "civic_police",
	Constants.Building.FIRE_STATION: "civic_fire_station",
	Constants.Building.SCHOOL: "civic_school",
	Constants.Building.HOSPITAL: "civic_hospital",
	Constants.Building.PARK: "civic_park",
}

const ZONE_PREFIX := {
	Constants.Zone.RES: "res",
	Constants.Zone.COM: "com",
	Constants.Zone.IND: "ind",
}


static func tex(name: String) -> Texture2D:
	if _cache.has(name):
		return _cache[name]
	var path := DIR + name + ".png"
	var t: Texture2D = null
	if ResourceLoader.exists(path):
		t = load(path)
	else:
		push_warning("Missing sprite: %s" % path)
	_cache[name] = t
	return t


static func zone_sprite(zone: int, density: int, level: int, wealth: int) -> String:
	return "%s_d%d_l%d_w%d" % [ZONE_PREFIX[zone], clampi(density, 1, 3), clampi(level, 1, 3), clampi(wealth, 1, 3)]


static func lot_sprite(zone: int, density: int) -> String:
	return "lot_%s_%d" % [ZONE_PREFIX[zone], clampi(density, 1, 3)]


static func civic_sprite(building: int) -> String:
	return CIVIC_SPRITES.get(building, "")


## Draws `name` so its footprint (side `fsize` tiles) starts at tile (x, y).
## Returns the drawn rectangle in world space, or an empty Rect2 if the sprite is missing.
static func draw(ci: CanvasItem, name: String, x: int, y: int, fsize: int = 1, modulate: Color = Color.WHITE) -> Rect2:
	var t := tex(name)
	if t == null:
		return Rect2()
	var top := IsoMath.tile_to_screen(x, y)
	var size := t.get_size()
	var pos := Vector2(top.x - IsoMath.HW * fsize, top.y + Constants.TILE_H * fsize - size.y)
	ci.draw_texture(t, pos, modulate)
	return Rect2(pos, size)


## Draws `name` centred on a world-space point (icons, smoke).
static func draw_centered(ci: CanvasItem, name: String, center: Vector2, modulate: Color = Color.WHITE, scale: float = 1.0) -> void:
	var t := tex(name)
	if t == null:
		return
	var size := t.get_size() * scale
	ci.draw_texture_rect(t, Rect2(center - size * 0.5, size), false, modulate)
