extends Node
## Background music. Autoloaded as `Music` so it keeps playing across the menu and the
## game. The track is a placeholder 30-second jazz loop generated by
## tools/generate_music.py; replace the file to change it.

const TRACK := "res://assets/audio/jazz_loop.wav"
const DEFAULT_VOLUME_DB := -14.0

var _player: AudioStreamPlayer
var enabled := true


func _ready() -> void:
	_player = AudioStreamPlayer.new()
	_player.bus = "Master"
	_player.volume_db = DEFAULT_VOLUME_DB
	add_child(_player)
	var stream = load(TRACK) if ResourceLoader.exists(TRACK) else null
	if stream == null:
		push_warning("Background music missing: %s. Run tools/generate_music.py." % TRACK)
		return
	# The file is a single bar-aligned loop, so play it round rather than once.
	if stream is AudioStreamWAV:
		stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
		stream.loop_begin = 0
		stream.loop_end = 0
	_player.stream = stream
	if enabled:
		_player.play()


func set_enabled(on: bool) -> void:
	enabled = on
	if _player == null or _player.stream == null:
		return
	if on and not _player.playing:
		_player.play()
	elif not on and _player.playing:
		_player.stop()


func is_playing() -> bool:
	return _player != null and _player.playing


func set_volume_db(db: float) -> void:
	if _player != null:
		_player.volume_db = db
